name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # prevents the workflow from doubling up if we make multiple deployments or commits at the same time
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.18.0"

      - name: Install
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
